name: PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    name: Lint, typecheck & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v6.0.2

      - uses: jdx/mise-action@d5d61992ae8b09ad81540a33e33b2d8226cce8af # v3.6.3

      - name: Install dependencies
        run: mise run setup

      - name: Lint
        run: mise run lint

      - name: Typecheck
        run: mise run typecheck

      - name: Build
        run: mise run build
